version: "3.9"

services:
  # Database 
  database:
    image: postgres:15-alpine3.18
    env_file:
      - path: ./app/backend/database.env
        required: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Frontend
  frontend:
    build:
      context: ./app/frontend
    develop:
      watch:
        - action: rebuild
          path: ./app/frontend
          target: /app/frontend
    ports:
      - 3000:3000
    depends_on:
      - database

  # Backend
  backend:
    build:
      context: ./app/backend
    env_file:
      - path: ./app/backend/database.env
        required: true
      - path: ./app/backend/backend.env
        required: true
    tty: true
    develop:
      watch:
        - action: rebuild
          path: ./app/backend
          target: /app/backend
    ports:
      - 5150:5150
    depends_on:
      - frontend
      - database
    # profiles:
    #   - test
    #   - build
    #   - dev
      
  # Adminer for a database ui
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

# For persistent data across builds
volumes:
  postgres_data: