version: "3.9"

services:
  # Database will be postgres
  # - Normally would use a volume for persistent data but for ease of use will avoid for this
  database:
    image: postgres:15-alpine3.18
    env_file:
      - path: ./app/backend/database.env
        required: true
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # frontend
  frontend:
    build:
      context: ./app/frontend
    develop:
      watch:
        - action: rebuild
          path: ./app/frontend
          target: /app/frontend
    ports:
      - 3000:80
    depends_on:
      - database

  # The backend, straight forward configuration
  backend:
    build:
      context: ./app/backend
    env_file:
      - path: ./app/backend/database.env
        required: true
      - path: ./app/backend/backend.env
        required: true
    tty: true
    develop:
      watch:
        - action: rebuild
          path: ./app/backend
          target: /application/app
    volumes:
      - ./app/backend:/app/backend
    ports:
      - 5150:5150
    depends_on:
      - frontend
      - database
      
  # Adminer for a database ui
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  postgres_data: